"""Generate a markdown digest from papers and articles."""
from __future__ import annotations

from pathlib import Path
from typing import List

from research_digest.arxiv_client import Paper
from research_digest.rss_client import Article
from research_digest.summarizer import Summary


def render_digest(
    papers: List[Paper],
    articles: List[Article],
    paper_summaries: List[Summary],
    article_summaries: List[Summary],
    title: str = "Research Digest",
    date: str = "",
) -> str:
    """Return a markdown string combining papers and articles."""
    lines = [f"# {title}", ""]
    if date:
        lines.append(f"**Date:** {date}")
        lines.append("")

    lines.append("## arXiv Papers")
    lines.append("")
    if not papers:
        lines.append("_No papers fetched._")
        lines.append("")
    for i, (p, s) in enumerate(zip(papers, paper_summaries), 1):
        lines.append(f"### {i}. {p.title}")
        lines.append(f"- **Authors:** {', '.join(p.authors[:4])}{' et al.' if len(p.authors) > 4 else ''}")
        lines.append(f"- **Published:** {p.published} | **Category:** {p.primary_category}")
        lines.append(f"- **PDF:** [{p.pdf_url}]({p.pdf_url})")
        lines.append(f"- **arXiv ID:** [{p.arxiv_id}](https://arxiv.org/abs/{p.arxiv_id})")
        if p.comment:
            lines.append(f"- **Comment:** {p.comment}")
        lines.append("")
        lines.append(f"**{s.headline}**")
        lines.append("")
        for pt in s.key_points:
            lines.append(f"- {pt}")
        lines.append("")
        lines.append(f"_Relevance:_ {s.relevance}")
        lines.append("")
        lines.append("---")
        lines.append("")

    lines.append("## RSS / Blog Articles")
    lines.append("")
    if not articles:
        lines.append("_No articles fetched._")
        lines.append("")
    for i, (a, s) in enumerate(zip(articles, article_summaries), 1):
        lines.append(f"### {i}. {a.title}")
        lines.append(f"- **Source:** {a.feed_name or 'RSS'}")
        lines.append(f"- **Published:** {a.published}")
        lines.append(f"- **Link:** [{a.link}]({a.link})")
        if a.authors:
            lines.append(f"- **Authors:** {', '.join(a.authors)}")
        lines.append("")
        lines.append(f"**{s.headline}**")
        lines.append("")
        for pt in s.key_points:
            lines.append(f"- {pt}")
        lines.append("")
        lines.append(f"_Relevance:_ {s.relevance}")
        lines.append("")
        lines.append("---")
        lines.append("")

    lines.append("*Generated by research-digest* 🦑")
    return "\n".join(lines)


def save_digest(md: str, out_path: Path) -> Path:
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(md, encoding="utf-8")
    return out_path
